### PR TITLE
Xml requests for creating tickets

### PR DESCRIPTION
**Pull request by aleg**
Hey mate,
in these days I've added the support for the XML content type (to create new tickets).
I've also made some changes to the search APIs and added the unit tests (so you don't have to have a working Codebase account). You can run the tests using `make runtests-install` if you run them for the first time. Later you can just use `make runtests` or `make runtests-all` for both unit and functional tests.

Cheers,
Ale

### CODE REVIEW

**Comment by igniteflow** [comment]
@aleg sorry I've only just seen this!  Will review over the weekend :-)

**Comment by afieldio** [comment]
Nice work AleG! This has been super useful. You can only post notes to a ticket with xml?! 

FYI - my pull request is still valid - you do not need to use urllib.urlencode for the json data structure in the handle response method. Instead use the below.

if c_type == self.CTYPE_XML:
    return xmltodict.parse(content)
return json.loads(content)

**Comment by igniteflow** [comment]
@afieldio notes can be posted as JSON or XML.  An example of a JSON post can be seen in [`codebase.utils`](https://github.com/igniteflow/codebase-python-api-client/blob/master/codebase/utils.py).

**Comment by aleg** [comment]
Thanks :) I made those changes because of some adjustment I had to do on the HW project.

For what I remember (it's been 6 months now), the XML request is required for creating a ticket. Once it's created, you can just use JSON for everything else.
Using JSON to create a ticket was failing for some reason (I must have read something in their API doc, but cannot remember now).

If the change looks good, you can merge and then add Adam's changes on top (during the merge probably).

**Comment by igniteflow** [comment]
Great stuff @aleg merged!  Thanks for adding the tests too, good Makefile skillz :-)

**Pull request merged**
